language: python
python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: bionic
      sudo: true
before_install:
  - sudo apt install -y gfortran
install:
  - pip install -U setuptools wheel pip
  - pip install -r requirements.txt
  - pip install pytest pytest-cov coveralls
  - pip install --no-deps --install-option="--with_pdd" -e .
script:
  - pytest --cov=solcore/
after_success:
  - coveralls
