language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get install -y gfortran
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install --no-depts --install-option="--with_pdd" .
script:
  - pytest --cov=solcore/
after_success:
  - coveralls
