name: Upload Python Package

on:
  # release:
  #   types: [published]
  push:
    # branches:
    #   - 'fix_deploy/*'

jobs:

  deploy_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Building for ${{ matrix.os }} - python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install system dependencies in Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt install -y gfortran python3-tk libboost-all-dev libopenblas-dev libfftw3-dev libsuitesparse-dev

      - name: Install system dependencies in MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew reinstall gfortran

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade setuptools wheel pip twine numpy==1.21.4

      - name: Build Solcore Windows
        if: matrix.os == 'windows-latest'
        env:
          FC: gfortran
          CC: gcc
          SOLCORE_WITH_PDD: 1
        run: |
          echo "[build]`ncompiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg
          python setup.py sdist bdist_wheel
        shell: powershell

      - name: Build Solcore Linux and MacOS
        if: matrix.os != 'windows-latest'
        env:
          FC: gfortran
          CC: gcc
          SOLCORE_WITH_PDD: 1
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
          python setup.py sdist bdist_wheel

      # - name: Publish wheels to PyPI
      #   env:
      #     TWINE_USERNAME: '__token__'
      #     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      #   run: |
      #     twine upload --skip-existing dist/*.whl

      - uses: actions/upload-artifact@v3
        with:
          name: OS wheels
          path: dist/