name: Test

on:
  push:
  pull_request:

env:
  PYTHON_VERSION: 3.9

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test_devpy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install -y gfortran ngspice python3-tk libboost-all-dev libopenblas-dev libfftw3-dev libsuitesparse-dev

      - name: Install Python dependecies
        run: |
          pip install pytest meson-python ninja cython numpy git+https://github.com/scientific-python/devpy
          pip install .[test]

      - name: Install S4
        run: |
          git clone https://github.com/phoebe-p/S4
          cd S4
          #make boost
          make S4_pyext
          cd ..
          rm -rf S4    

      - name: Build solcore
        run: |
          python -m devpy build   

      - name: Test
        env:
          SOLCORE_SPICE: ngspice
        run: |
          python -m devpy test
